import type { ColumnConfig, FieldConfig } from "@/components/entity-table";

export const configs: Record<string, { title: string; fields: FieldConfig[]; columns: ColumnConfig[] }> = {
  tasks: { title: "Tasks", columns: [{key:"task_code",label:"Code"},{key:"title",label:"Task"},{key:"work_package_id",label:"AP"},{key:"status",label:"Status",badge:true},{key:"priority",label:"Priority",badge:true},{key:"blocking",label:"Blocking"},{key:"responsible",label:"Responsible"}], fields: [
    {key:"work_package_id",label:"Work package",type:"select",required:true},{key:"task_code",label:"Task code",required:true},{key:"title",label:"Title",required:true},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["open","waiting","in_progress","blocked","done"],required:true},{key:"priority",label:"Priority",type:"select",options:["low","medium","high","critical"],required:true},{key:"blocking",label:"Blocking",type:"checkbox"},{key:"responsible",label:"Responsible"},{key:"dependency",label:"Dependency"},{key:"due_date",label:"Due date",type:"date"},{key:"notes",label:"Notes",type:"textarea"},{key:"sort_order",label:"Sort order",type:"number"}] },
  open_questions: { title:"Open Questions", columns:[{key:"question_code",label:"Code"},{key:"question",label:"Question"},{key:"work_package_id",label:"AP"},{key:"status",label:"Status",badge:true},{key:"blocking",label:"Blocking"},{key:"next_action",label:"Next action"}], fields:[
    {key:"work_package_id",label:"Work package",type:"select",required:true},{key:"question_code",label:"Question code",required:true},{key:"question",label:"Question",type:"textarea",required:true},{key:"status",label:"Status",type:"select",options:["not_asked","asked","answered","obsolete"]},{key:"blocking",label:"Blocking",type:"checkbox"},{key:"answer",label:"Answer",type:"textarea"},{key:"next_action",label:"Next action"},{key:"notes",label:"Notes",type:"textarea"}] },
  decisions: { title:"Decisions", columns:[{key:"decision_code",label:"Code"},{key:"title",label:"Decision"},{key:"work_package_id",label:"AP"},{key:"status",label:"Status",badge:true},{key:"selected_option",label:"Selected option"},{key:"dependent_on",label:"Dependent on"}], fields:[
    {key:"work_package_id",label:"Work package",type:"select",required:true},{key:"decision_code",label:"Decision code",required:true},{key:"title",label:"Title",required:true},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["open","pending","decided"]},{key:"selected_option",label:"Selected option"},{key:"dependent_on",label:"Dependent on"},{key:"notes",label:"Notes",type:"textarea"}] },
  stakeholders: { title:"Stakeholders", columns:[{key:"name",label:"Name"},{key:"organizational_unit",label:"Organization"},{key:"role",label:"Role"},{key:"responsibility",label:"Responsibility"}], fields:[
    {key:"name",label:"Name",required:true},{key:"organizational_unit",label:"Organizational unit"},{key:"role",label:"Role"},{key:"responsibility",label:"Responsibility",type:"textarea"},{key:"notes",label:"Notes",type:"textarea"}] },
  access_requests: { title:"Access", columns:[{key:"system_name",label:"System"},{key:"work_package_id",label:"AP"},{key:"status",label:"Status",badge:true},{key:"responsible",label:"Responsible"},{key:"description",label:"Description"}], fields:[
    {key:"work_package_id",label:"Work package",type:"select",required:true},{key:"system_name",label:"System name",required:true},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["unknown","required","requested","granted","rejected","not_required"]},{key:"responsible",label:"Responsible"},{key:"notes",label:"Notes",type:"textarea"}] },
  roadmap_items: { title:"Roadmap Items", columns:[{key:"title",label:"Item"},{key:"work_package_id",label:"AP"},{key:"week_number",label:"Start week"},{key:"start_date",label:"Start"},{key:"end_date",label:"End"},{key:"status",label:"Status",badge:true}], fields:[
    {key:"work_package_id",label:"Work package",type:"select",required:true},{key:"title",label:"Title",required:true},{key:"description",label:"Description",type:"textarea"},{key:"week_number",label:"Week number",type:"number"},{key:"start_date",label:"Start date",type:"date"},{key:"end_date",label:"End date",type:"date"},{key:"status",label:"Status",required:true},{key:"dependency",label:"Dependency"},{key:"sort_order",label:"Sort order",type:"number"}] },
};